### ISSUE TITLE
model.restore() eats all the GPU memory causing OOM error later on

### ISSUE THREAD

**Issue by albertma-evotec** [deepchem/deepchem#2133]
I have tried to load my saved GC model. I intended to use the model to predict properties but for now I will just skip the prediction so the following issues are not caused by model.predict. I monitored the GPU usage and I found it quickly eats up all my GPU memory. I don't want this to happen because I need to have spare memory for my reinforcement learning loop (using pytorch) plus I thought loading a GC model shouldn't take up so much GPU capacity.

```
my_GC_model = GraphConvModel(1, batch_size=128, mode='regression', model_dir='/my/mode/directory')
my_GC_model.restore()
```
![image](https://user-images.githubusercontent.com/54853041/91836330-844f2f00-ec42-11ea-96ef-bbf975febccd.png)


In my shell I have set CUDA_VISIBLE_DEVICES=2,3

I created a environment that is differ from the original deepchem because I am running a reinforcement learning task in which I use the deepchem GC model prediction as part of the scoring function. pip list as below.

Package                Version                                                                                                                                                                                                               
---------------------- --------------------------                                                                                                                                                                                            
absl-py                0.9.0                                                                                                                                                                                                                 
aiohttp                3.6.2                                                                                                                                                                                                                 
asn1crypto             1.3.0                                                                                                                                                                                                                 
astor                  0.7.1                                                                                                                                                                                                                 
astunparse             1.6.3                                                                                                                                                                                                                 
async-timeout          3.0.1                                                                                                                                                                                                                 
attrs                  19.3.0                                                                                                                                                                                                                
backcall               0.1.0                                                                                                                                                                                                                 
beautifulsoup4         4.9.1                                                                                                                                                                                                                 
bleach                 3.1.5                                                                                                                                                                                                                 
brotlipy               0.7.0                                                                                                                                                                                                                 
cachetools             4.1.1                                                                                                                                                                                                                 
certifi                2020.4.5.1                                                                                                                                                                                                            
cffi                   1.14.0                                                                                                                                                                                                                
chardet                3.0.4                                                                                                                                                                                                                 
click                  7.1.2                                                                                                                                                                                                                 
colorama               0.4.3                                                                                                                                                                                                                 
cryptography           2.5                                                                                                                                                                                                                   
cycler                 0.10.0                                                                                                                                                                                                                
Cython                 0.29.19                                                                                                                                                                                                               
dataclasses            0.7                                                                                                                                                                                                                   
decorator              4.4.2                                                                                                                                                                                                                 
deepchem               2.4.0rc1.dev20200804160324                                                                                                                                                                                            
defusedxml             0.6.0                                                                                                                                                                                                                 
dill                   0.3.1.1                                                                                                                                                                                                               
entrypoints            0.3                                                                                                                                                                                                                   
filelock               3.0.12                                                                                                                                                                                                                
gast                   0.3.3                                                                                                                                                                                                                 
google                 2.0.3                                                                                                                                                                                                                 
google-auth            1.20.1                                                                                                                                                                                                                
google-auth-oauthlib   0.4.1                                                                                                                                                                                                                 
google-pasta           0.2.0                                                                                                                                                                                                                 
grpcio                 1.16.0                                                                                                                                                                                                                
h5py                   2.10.0                                                                                                                                                                                                                
idna                   2.8                                                                                                                                                                                                                   
idna-ssl               1.1.0                                                                                                                                                                                                                 
importlib-metadata     1.6.0                                                                                                                                                                                                                 
ipykernel              5.3.0                                                                                                                                                                                                                 
ipython                7.14.0                                                                                                                                                                                                                
ipython-genutils       0.2.0                                                                                                                                                                                                                 
ipywidgets             7.5.1                                                                                                                                                                                                                 
jedi                   0.17.0                                                                                                                                                                                                                
Jinja2                 2.11.2                                                                                                                                                                                                                
joblib                 0.15.1                                                                                                                                                                                                                
jsonschema             3.2.0                                                                                                                                                                                                                 
jupyter-client         6.1.3                                                                                                                                                                                                                 
jupyter-console        6.1.0                                                                                                                                                                                                                 
jupyter-core           4.6.3                                                                                                                                                                                                                 
Keras-Applications     1.0.8                                                                                                                                                                                                                 
Keras-Preprocessing    1.1.0                                                                                                                                                                                                                 
kiwisolver             1.2.0                                                                                                                                                                                                                 
lxml                   3.8.0                                                                                                                                                                                                                 
Markdown               3.2.2                                                                                                                                                                                                                 
MarkupSafe             1.1.1                                                                                                                                                                                                                 
matplotlib             3.1.1                                                                                                                                                                                                                 
mdtraj                 1.9.1                                                                                                                                                                                                                 
mistune                0.8.4                                                                                                                                                                                                                 
mkl-service            2.3.0                                                                                                                                                                                                                 
mock                   4.0.2                                                                                                                                                                                                                 
more-itertools         8.3.0                                                                                                                                                                                                                 
msgpack                0.6.2                                                                                                                                                                                                                 
multidict              4.7.6                                                                                                                                                                                                                 
multiprocess           0.70.9                                                                                                                                                                                                                
nbconvert              5.6.1                                                                                                                                                                                                                 
nbformat               5.0.6                                                                                                                                                                                                                 
networkx               2.4                                                                                                                                                                                                                   
notebook               6.0.3                                                                                                                                                                                                                 
numexpr                2.7.1                                                                                                                                                                                                                 
numpy                  1.17.3                                                                                                                                                                                                                
oauthlib               3.1.0                                                                                                                                                                                                                 
olefile                0.46                                                                                                                                                                                                                  
OpenMM                 7.4.2                                                                                                                                                                                                                 
opt-einsum             3.3.0                                                                                                                                                                                                                 
packaging              20.4                                                                                                                                                                                                                  
pandas                 0.25.3                                                                                                                                                                                                                
pandocfilters          1.4.2                                                                                                                                                                                                                 
parso                  0.7.0                                                                                                                                                                                                                 
pathos                 0.2.5                                                                                                                                                                                                                 
pdbfixer               1.6                                                                                                                                                                                                                   
pexpect                4.8.0                                                                                                                                                                                                                 
pickleshare            0.7.5                                                                                                                                                                                                                 
Pillow                 7.1.2                                                                                                                                                                                                                 
pip                    20.1.1                                                                                                                                                                                                                
pluggy                 0.13.1                                                                                                                                                                                                                
pox                    0.2.7                                                                                                                                                                                                                 
ppft                   1.6.6.1                                                                                                                                                                                                               
prometheus-client      0.8.0                                                                                                                                                                                                                 
prompt-toolkit         3.0.5                                                                                                                                                                                                                 
protobuf               3.11.4                                                                                                                                                                                                                
ptyprocess             0.6.0                                                                                                                                                                                                                 
py                     1.8.1                                                                                                                                                                                                                 
py-spy                 0.3.3                                                                                                                                                                                                                 
pyasn1                 0.4.8                                                                                                                                                                                                                 
pyasn1-modules         0.2.8                                                                                                                                                                                                                 
pycparser              2.20
Pygments               2.6.1
pyOpenSSL              19.0.0
pyparsing              2.4.7
pyrsistent             0.16.0
PySocks                1.7.1
pytest                 5.3.0
python-dateutil        2.8.1
python-pptx            0.6.18
pytz                   2020.1
PyYAML                 5.3.1
pyzmq                  19.0.1
qtconsole              4.7.4
QtPy                   1.9.0
ray                    0.8.5
redis                  3.4.1
requests               2.22.0
requests-oauthlib      1.3.0
rsa                    4.6
scikit-learn           0.21.3
scipy                  1.4.1
Send2Trash             1.5.0
setuptools             46.4.0.post20200518
simdna                 0.4.2
six                    1.15.0
soupsieve              2.0.1
tables                 3.6.1
tensorboard            2.2.2
tensorboard-plugin-wit 1.7.0
tensorflow             2.2.0
tensorflow-estimator   2.2.0
termcolor              1.1.0
terminado              0.8.3
testpath               0.4.4
torch                  1.3.1
tornado                6.0.4
tqdm                   4.38.0
traitlets              4.3.3
typing-extensions      3.7.4.2
urllib3                1.25.9
wcwidth                0.1.9
webencodings           0.5.1
Werkzeug               1.0.1
wheel                  0.34.2
widgetsnbextension     3.5.1
wrapt                  1.12.1
XlsxWriter             1.2.8
yarl                   1.4.2
zipp                   3.1.0

**Comment by nd-02110114** [comment]
I think this is an expected situation.
Please confirm how TensorFlow use GPU from https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth 

> By default, TensorFlow maps nearly all of the GPU memory of all GPUs (subject to CUDA_VISIBLE_DEVICES) visible to the process.

If you want to avoid eating up all your GPU memory,  maybe you need to assign a different GPU to TensorFlow (use GPU2) and PyTorch (use GPU3) explicitly.

**Comment by rbharath** [comment]
A second point here is that `GraphConvModel` saving/restoring has a couple of known problems (https://github.com/deepchem/deepchem/issues/2013). This is definitely on our TODO list to fix, but something to be cautious of right now.

**Comment by albertma-evotec** [comment]
I found add this code can avoid the memory being used up.

```
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
  try:
    for gpu in gpus:
      tf.config.experimental.set_memory_growth(gpu, True)
  except RuntimeError as e:
    print(e)
```

**Comment by nd-02110114** [comment]
I seem this issue was resolved, so close it
