### ISSUE TITLE
model.fit(train_dataset, nb_epoch=100) fails during DeepChem tutorial

### ISSUE THREAD

**Issue by hhg7** [deepchem/deepchem#4432]
## To Reproduce

import deepchem as dc
```
>>> dc.__version__
'2.5.0'
>>> tasks, datasets, transformers = dc.molnet.load_delaney(featurizer='GraphConv')
>>> 
>>> train_dataset, valid_dataset, test_dataset = datasets
>>> model = dc.models.GraphConvModel(n_tasks=1, mode='regression', dropout=0.2,batch_normalize=False)
2025-04-27 08:43:48.624007: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)
>>> model = dc.models.GraphConvModel(n_tasks=1, mode='regression', dropout=0.2,batch_normalize=False)
>>> 
>>> 
>>> model.fit(train_dataset, nb_epoch=100)
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/con/.local/lib/python3.12/site-packages/deepchem/models/keras_model.py", line 320, in fit
    return self.fit_generator(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/con/.local/lib/python3.12/site-packages/deepchem/models/keras_model.py", line 398, in fit_generator
    self._create_training_ops(batch)
  File "/home/con/.local/lib/python3.12/site-packages/deepchem/models/keras_model.py", line 260, in _create_training_ops
    self._create_inputs(example_batch[0])
  File "/home/con/.local/lib/python3.12/site-packages/deepchem/models/keras_model.py", line 245, in _create_inputs
    if (self.model.inputs is not None) and len(self.model.inputs) > 0:
        ^^^^^^^^^^^^^^^^^
AttributeError: '_GraphConvKerasModel' object has no attribute 'inputs'. Did you mean: 'input'?
```
## Expected behavior
whatever was supposed to happen on the tutorial

whatever was supposed to happen on the tutorial
## Environment

* OS:Ubuntu 24.04.2 LTS
* Python version: 3.12.3
* DeepChem version:'2.5.0'
* RDKit version (optional): 2024.09.6
* TensorFlow version (optional):
* PyTorch version (optional):
* Any other relevant information:

## Additional context

I cannot finish the tutorial

**Comment by heilcheng** [comment]
May I know which tutorial is it?

**Comment by leminhds** [comment]
also have issue with this same tutorial, which is litterally the first tutorial??

**Comment by satyam102006** [comment]
https://colab.research.google.com/drive/12Z2dJr0S9GqBmYcV9l2PyjFb6Fw6yuAM?usp=sharing  
check i done changes in my code 
The old `GraphConvKerasModel` is deprecated in newer versions of DeepChem. This commit updates the script to use the unified `GraphConvModel` to ensure compatibility.    older one has inputs and newer one has input

**Comment by koushikcs562** [comment]
Thanks for reporting this! I ran into the same issue and it seems to stem from a mismatch between the tutorial code and the current DeepChem version. The `GraphConvModel` now wraps a Keras model that uses `.input` instead of `.inputs`, which breaks compatibility with older internal calls in `fit()`.

A workaround that worked for me was to downgrade to DeepChem 2.6.0 or earlier, or alternatively, modify the tutorial to use the updated API and ensure TensorFlow is properly installed. Also, make sure you're not using Python 3.12, as some dependencies (like TensorFlow) may not yet fully support it.

Happy to help test or update the tutorial notebook if needed!

**Comment by ShreyasN707** [comment]
@hhg7 i would like to work on this issue please assign this to me.
